config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  
  resources :worlds do 
    resources :characters, :plots
  end

  #resources :worlds do
   # resources :plots
  #end

  resources :characters 
  resources :plots

  root 'application#home'
 
  #nested show url
  #get 'worlds/:world_id/characters/:character_id'       
  #get 'worlds/:world_id/plots/:plot_id' 
        

  #nested new url
  #get 'worlds/:world_id/characters/new' 
  #get 'worlds/:world_id/plots/new' 
        
  #form display with validations
  #in view folder world, under form
  
  #custom active record scope 
  #view world with most plots 
  get 'worlds/most-plots' => 'worlds#show'


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


  devise_for :users, :controllers => { registrations: "registrations",
     omniauth_callbacks: "callbacks"}

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
 
end

app/models/world.rb
class World < ApplicationRecord
    belongs_to :user
        #when delete world, deletes chars and plots
    has_many :characters, :dependent => :destroy
    accepts_nested_attributes_for :characters
    
    has_many :plots, :dependent => :destroy
    accepts_nested_attributes_for :plots

    validates :name, presence: true
    #validates :genre, presence: true 

    #most plots in a world
    def self.most_plots
        joins(:plots).group("worlds.id").order("COUNT(*) DESC").select("worlds.*").limit(1)
    end

end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_world, except: [:index, :new, :create, :show, :destroy]

    def index
        @worlds = World.all
   end

    def show
        if params[:id] == "most-plots"
            @world = World.most_plots.first
        else
            set_world
        end
        @characters = @world.characters
        @plots = @world.plots
      
    end

    def character
        @character = Character.find(params[:character_id])
        render template: 'characters/show'
    end

    def plot
        @plot = Plot.find(params[:plot_id])
        render template: 'plots/show'
    end

    def new
        @world = World.new
    end

    def create
       # @world = World.new(world_params)
        @world = current_user.worlds.build(world_params)

        if @world.save
            flash[:notice] = "World was Sucessfully created!"
            redirect_to world_path(@world)
        else
            flash[:alert] = "World not created. Try again."
            render '/worlds/new'
        end 
    end

    def edit
        @world = World.find(params[:id])
    end

    def update
        #@world.update(world_params)
        @world = World.find(params[:id])

        if @world.update(world_params)
            redirect_to world_path(@world)
        else
            flash[:errors] = @world.errors.full_messages
            render :edit
        end
    end

    def destroy
      @world = World.find(params[:id])
      @world.destroy

      redirect_to worlds_path
    end

    private 

    def world_params
        params.require(:world).permit(
            :name,
            :genre,
            :description,
            :aesthetic
        )
    end

end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/worlds/_form.html.erb
<%= form_for(world) do |f| %>
    <label class="label">world name:</label>
    <%= f.text_field :name %><br><br>

    <label class="label">aesthetic:</label>
    <%= f.text_field :aesthetic %><br><br>

    <label class="label">genre:</label>
    <%= f.text_field :genre %><br><br>

    <label class="label">description:</label>
    <%= f.text_field :description %><br><br>

    <input type="submit" value="Submit" class="button is-primary">
<% end %>

app/views/worlds/_list.html.erb
<ul>
<% worlds.each do |w| %>

    <li><%= link_to w.name, world_path(w) %> ||
   </li> 
   
<% end %>
</ul>

app/views/worlds/edit.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">Edit <%= @world.name %></h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {world: @world} %>

<br>


<%= form_tag(world_path(@world), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/worlds/index.html.erb
<h1> Worlds </h1>

<div>
    <strong><%= link_to "Create a New world", new_world_path %></strong>
    </div>
    <br>
   


<ul>
<div>
<%= render partial: "worlds/list", locals: {worlds: @worlds} %>
</div>
</ul>

<br>

 <div>
   


    

app/views/worlds/new.html.erb
<h1>New World</h1>

<%= render 'form', world: @world %>

<%= link_to 'Back', worlds_path %>

app/views/worlds/show.html.erb
<% if @world.user_id == current_user.id %>
    <%= link_to "Edit world", edit_world_path(@world) %> <br>
    <%= link_to "new character", new_world_character_path(@world) %> <br>
    <%= link_to "new plot", new_world_plot_path(@world) %>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @world.name %>
</p>
 
<p>
  <strong>Genre:</strong>
  <%= @world.genre %>
</p>
 
<p>
  <strong>Aesthetic:</strong>
  <%= @world.aesthetic %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @world.description %>
</p>

            <h3>All characters at <%= @world.name %></h3>
            <div>
            <%= render partial: "characters/list", locals: {characters: @characters} %>
            </div>


  <h3>plots for <%= @world.name %> </h3>
            <% @plots.each do |p| %>
                
                  <li><%= link_to p.title, world_plot_path(p.world, p) %></li>
 
            <% end %>
            <br>

<%= link_to 'Back', worlds_path %>