config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  
  resources :worlds do 
    resources :characters, :plots
  end

  #resources :worlds do
   # resources :plots
  #end

  resources :characters 
  resources :plots

  root 'application#home'
 
  #nested show url
  #get 'worlds/:world_id/characters/:character_id'       
  #get 'worlds/:world_id/plots/:plot_id' 
        

  #nested new url
  #get 'worlds/:world_id/characters/new' 
  #get 'worlds/:world_id/plots/new' 
        
  #form display with validations
  #in view folder world, under form
  
  #custom active record scope 
  #view world with most plots 
  get 'worlds/most-plots' => 'worlds#show'


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


  devise_for :users, :controllers => { registrations: "registrations",
     omniauth_callbacks: "callbacks"}

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
 
end

app/models/plot.rb
class Plot < ApplicationRecord
    belongs_to :world
    

    validates :title, presence: true
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_world
    before_action :set_plot, except: [:index, :new, :create, :show, :destroy]

    def index
        redirect_to worlds_path(@worlds)
    end

    def show
       # @plot = plot.find(params[:id])
        set_plot
    end

    def new
        @plot = @world.plots.build
    end

    def create
        @plot = Plot.new(plot_params)
        #@plot = current_user.plots.build(plot_params)
        @plot.user_id = current_user.id

          if @plot.valid?
            @plot.save
            redirect_to worlds_path(@plot)
          else
            flash[:errors] = @plot.errors.full_messages
            render :new
        end
    end

    def edit
       @plot = Plot.find(params[:id])
    end

    def update
        #@plot.update(plot_params)
        @plot = Plot.find(params[:id])
        
        if @plot.update(plot_params)
            redirect_to worlds_path(@worlds)
        else
            flash[:errors] = @plot.errors.full_messages
            render :edit
        end
    end

    def destroy
        @plot = Plot.find(params[:id])
        @plot.destroy

        redirect_to plots_path 
    end

    private 

    def plot_params
        params.require(:plot).permit(
            :title,
            :importance,
            :description,
            :user_id,
            :world_id
        )
    end

    def set_world
        @world = World.find_by(id:params[:world_id])
    end

end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/views/plots/_form.html.erb
<%= form_for(@plot) do |f| %>


 <% if @plot.world.nil? %>
        <label class="label">plot world:</label>
        <%= f.select :world_id, options_from_collection_for_select(World.all, :id, :title) %><br>
        <i>Don't see your world? Create a new world <%= link_to "here.", new_world_path %></i><br><br>
    <% else %>
        <%= hidden_field_tag "plot[world_id]", @plot.world_id %>
    <% end %>

    <label class="label"> title: </label>
    <%= f.text_field :title %><br><br>

    <label class="label">importance:</label>
    <%= f.text_field :importance %><br><br>

    <label class="label">Description:</label>
    <%= f.text_field :description %><br><br>
 
   <input type="submit" value="Submit" class="button is-primary">
<% end %>

app/views/plots/_list.html.erb
<ul>
    <% @plots.each do |p| %>
       <li><%= link_to p.title, world_plot_path(p.world, p) %></li>
    <% end %> 
</ul>

app/views/plots/edit.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">Edit <%= @plot.title %></h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {plot: @plot} %>

<br>

<%= form_tag(plot_path(@plot), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/plots/index.html.erb
<h1> hello </h1>

app/views/plots/new.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">New plot Form</h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {form_plot: @plot} %>

app/views/plots/show.html.erb
<strong>world:</strong> <%= link_to @world.name, world_path(@world) %> <br>
  
<% if @plot.user_id == current_user.id %>
    <%= link_to "Edit plot", edit_world_plot_path(@world) %> <br>
  <% else %>
  
<% end %>

<p>
  <strong>title:</strong>
  <%= @plot.title  %>
</p>

<p>
  <strong>plot importance:</strong>
  <%= @plot.importance %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @plot.description %>
</p>

 