config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  
  resources :worlds do 
    resources :characters, :plots
  end

  #resources :worlds do
   # resources :plots
  #end

  resources :characters 
  resources :plots

  root 'application#home'
 
  #nested show url
  #get 'worlds/:world_id/characters/:character_id'       
  #get 'worlds/:world_id/plots/:plot_id' 
        

  #nested new url
  #get 'worlds/:world_id/characters/new' 
  #get 'worlds/:world_id/plots/new' 
        
  #form display with validations
  #in view folder world, under form
  
  #custom active record scope 
  #view world with most plots 
  get 'worlds/most-plots' => 'worlds#show'


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


  devise_for :users, :controllers => { registrations: "registrations",
     omniauth_callbacks: "callbacks"}

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
 
end

app/models/character.rb
class Character < ApplicationRecord
    belongs_to :world


    validates :name, presence: true 
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_world
    before_action :set_character, except: [:index, :new, :create, :show, :destroy]

    def index
        redirect_to worlds_path(@worlds)
    end

    def show
       # @character = Character.find(params[:id])
        set_character
    end

    def new
        @character = @world.characters.build
    end

    def create
        @character = Character.new(character_params)
        #@character = current_user.characters.build(character_params)
        @character.user_id = current_user.id

          if @character.valid?
            @character.save
            redirect_to worlds_path(@worlds)
          else
            flash[:errors] = @character.errors.full_messages
            render :new
        end
    end

    def edit
       @character = Character.find(params[:id])
    end

    def update
        #@character.update(character_params)
        @character = Character.find(params[:id])
        @character.user_id = current_user.id

        if @character.update(character_params)
            redirect_to worlds_path(@worlds)
        else
            flash[:errors] = @character.errors.full_messages
            render :edit
        end
    end

    def destroy
        @character = Character.find(params[:id])
        @character.destroy

        redirect_to characters_path 
    end

    private 

    def character_params
        params.require(:character).permit(
            :name,
            :alignment,
            :species,
            :character_class,
            :description,
            :user_id,
            :world_id
        )
    end

    def set_world
        @world = World.find_by(id:params[:world_id])
    end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>

    <% if @character.world.nil? %>
        <label class="label">character world:</label>
        <%= f.select :world_id, options_from_collection_for_select(world.all, :id, :name) %><br>
        <i>Don't see your world? Create a new world <%= link_to "here.", new_world_path %></i><br><br>
    <% else %>
        <%= hidden_field_tag "character[world_id]", @character.world_id %>
    <% end %>

    <label class="label"> Name: </label>
    <%= f.text_field :name %><br><br>

    <label class="label">Character Class:</label>
    <%= f.text_field :character_class %><br><br>

    <label class="label">Alignment:</label>
    <%= f.text_field :alignment %><br><br>

    <label class="label">Species:</label>
    <%= f.text_field :species %><br><br>

    <label class="label">Description:</label>
    <%= f.text_field :description %><br><br>
    
    <%= f.hidden_field :user_id, value:current_user.id %>
 
   <input type="submit" value="Submit" class="button is-primary">
<% end %>

app/views/characters/_list.html.erb
<ul>
    <% @characters.each do |c| %>
       <li><%= link_to c.name, world_character_path(c.world, c) %></li>
    
    <% end %>
    <br>
  

</ul>

app/views/characters/edit.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">Edit <%= @character.name %></h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {character: @character} %>

<br>

<%= form_tag(character_path(@character), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/characters/new.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">New character Form</h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {form_character: @character} %>

app/views/characters/show.html.erb
<strong>world:</strong> <%= link_to @world.name, world_path(@world) %> <br>
  
<% if @character.user_id == current_user.id %>
    <%= link_to "Edit character", edit_world_character_path(@world) %> <br>
 
  <% else %>
 
<% end %>

<p>
  <strong>Name:</strong>
  <%= @character.name  %>
</p>
 
<p>
  <strong>alignment:</strong>
  <%= @character.alignment %>
</p>
 
<p>
  <strong>character_class:</strong>
  <%= @character.character_class %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>

<p>
  <strong>character species:</strong>
  <%= @character.species %>
</p>
 
         