config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  
  resources :worlds do 
    resources :characters, :plots
  end

  #resources :worlds do
   # resources :plots
  #end

  resources :characters 
  resources :plots

  root 'application#home'
 
  #nested show url
  #get 'worlds/:world_id/characters/:character_id'       
  #get 'worlds/:world_id/plots/:plot_id' 
        

  #nested new url
  #get 'worlds/:world_id/characters/new' 
  #get 'worlds/:world_id/plots/new' 
        
  #form display with validations
  #in view folder world, under form
  
  #custom active record scope 
  #view world with most plots 
  get 'worlds/most-plots' => 'worlds#show'


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


  devise_for :users, :controllers => { registrations: "registrations",
     omniauth_callbacks: "callbacks"}

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end
class ApplicationController < ActionController::Base
    helper_method :set_world, :set_character, :set_plot

    def home
        
    end 

    def set_world
        @world = World.find(params[:id])
    end

    def set_character
        @character = Character.find(params[:id])
    end

    def set_plot
        @plot = Plot.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if !!flash[:errors] %>
<ul>
<% flash[:errors].each do |e| %>
  <li><%= e %></li>
  <% end %>
</ul>
<% end %>

app/views/application/home.html.erb
<h1>Welcome to Worlding!</h1>
<p>Here you can share your world and character ideas, 
as well as read up on others.</p>
<br>
<br>
    <h3>Want the world with the most plots?</h3>
    <%= link_to "Click here", worlds_most_plots_path %> to view the world with the most plots.
    